<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Categorias Pagina:
                </div>
                <div class="panel-body">

                    <table class="table table-hover">
                        <thead>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>#</th>
                        </thead>
                        <tbody>

                        <?php foreach ($this->view->categories as $category)
                        {
                            echo "
                                <tr>
                                <td>{$category->id}</td>
                                <td>{$category->name}</td>
                                <td>
                                    <a href='/admin/' title=''><i class= 'glyphicon glyphicon-edit'></i></a>
                                </td>
                                </tr>";
                        }?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
