<script src="../../../../assets/ckeditor/ckeditor.js"></script>
<script src="../../../../assets/ckeditor/sample.js"></script>

<main>
    <input type="hidden" value="1" id="id">
    <div class="adjoined-top">
        <div class="grid-container">
            <div class="content grid-width-100">
                <h1>Editar</h1>
            </div>
        </div>
    </div>
    <div class="adjoined-bottom">
        <div class="grid-container">
            <div class="grid-width-100">
                <div id="editor">

                </div>
            </div>
        </div>
    </div>
    Total Caracteres: <span id="total"></span>
</main>
<script>
    initSample();
    var editor = CKEDITOR.instances.editor;
    editor.on( 'change', function( evt ) {
        //console.log( 'Total bytes: ' + evt.editor.getData().length );
        $("#total").html(evt.editor.getData().length )
    });
</script>
